<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>PawSharp.Commands</RootNamespace>
    <AssemblyName>PawSharp.Commands</AssemblyName>
    <PackageId>PawSharp.Commands</PackageId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\PawSharp.Core\PawSharp.Core.csproj" />
    <ProjectReference Include="..\PawSharp.API\PawSharp.API.csproj" />
    <ProjectReference Include="..\PawSharp.Client\PawSharp.Client.csproj" />
  </ItemGroup>

</Project>