#nullable enable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;
using PawSharp.Core.Enums;
using PawSharp.Core.Serialization;

namespace PawSharp.Core.Entities;

/// <summary>
/// Activity object attached to a Rich Presence message.
/// </summary>
public class MessageActivity
{
    /// <summary>Type of activity (1=Join, 2=Spectate, 3=Listen, 5=JoinRequest).</summary>
    [JsonPropertyName("type")]
    public int Type { get; set; }

    /// <summary>Party ID from the player's Rich Presence, if present.</summary>
    [JsonPropertyName("party_id")]
    public string? PartyId { get; set; }
}

/// <summary>
/// Partial application object attached to a Rich Presence message.
/// </summary>
public class MessageApplication
{
    [JsonPropertyName("id")]
    [JsonConverter(typeof(SnowflakeJsonConverter))]
    public ulong Id { get; set; }

    /// <summary>Cover image hash for the application.</summary>
    [JsonPropertyName("cover_image")]
    public string? CoverImage { get; set; }

    [JsonPropertyName("description")]
    public string Description { get; set; } = string.Empty;

    [JsonPropertyName("icon")]
    public string? Icon { get; set; }

    [JsonPropertyName("name")]
    public string Name { get; set; } = string.Empty;
}

/// <summary>
/// Represents a Discord message.
/// </summary>
public class Message : DiscordEntity
{
    /// <summary>
    /// Id of the channel the message was sent in.
    /// </summary>
    [JsonPropertyName("channel_id")]
    [JsonConverter(typeof(SnowflakeJsonConverter))]
    public ulong ChannelId { get; set; }
    
    /// <summary>
    /// The author of this message.
    /// </summary>
    [JsonPropertyName("author")]
    public User Author { get; set; } = null!;
    
    /// <summary>
    /// Contents of the message.
    /// </summary>
    [JsonPropertyName("content")]
    public string Content { get; set; } = string.Empty;
    
    /// <summary>
    /// When this message was sent.
    /// </summary>
    [JsonPropertyName("timestamp")]
    public DateTimeOffset Timestamp { get; set; }
    
    /// <summary>
    /// When this message was edited (or null if never).
    /// </summary>
    [JsonPropertyName("edited_timestamp")]
    public DateTimeOffset? EditedTimestamp { get; set; }
    
    /// <summary>
    /// Whether this was a TTS message.
    /// </summary>
    [JsonPropertyName("tts")]
    public bool Tts { get; set; }
    
    /// <summary>
    /// Whether this message mentions everyone.
    /// </summary>
    [JsonPropertyName("mention_everyone")]
    public bool MentionEveryone { get; set; }
    
    /// <summary>
    /// Users specifically mentioned in the message.
    /// </summary>
    [JsonPropertyName("mentions")]
    public List<User> Mentions { get; set; } = new();
    
    /// <summary>
    /// Roles specifically mentioned in this message.
    /// </summary>
    [JsonPropertyName("mention_roles")]
    public List<ulong> MentionRoles { get; set; } = new();
    
    /// <summary>
    /// Any attached files.
    /// </summary>
    [JsonPropertyName("attachments")]
    public List<Attachment> Attachments { get; set; } = new();
    
    /// <summary>
    /// Any embedded content.
    /// </summary>
    [JsonPropertyName("embeds")]
    public List<Embed> Embeds { get; set; } = new();
    
    /// <summary>
    /// Reactions to the message.
    /// </summary>
    [JsonPropertyName("reactions")]
    public List<Reaction>? Reactions { get; set; }
    
    /// <summary>
    /// Used for validating a message was sent.
    /// </summary>
    [JsonPropertyName("nonce")]
    public string? Nonce { get; set; }
    
    /// <summary>
    /// Whether this message is pinned.
    /// </summary>
    [JsonPropertyName("pinned")]
    public bool Pinned { get; set; }
    
    /// <summary>
    /// If the message is generated by a webhook, this is the webhook's id.
    /// </summary>
    [JsonPropertyName("webhook_id")]
    public ulong? WebhookId { get; set; }
    
    /// <summary>
    /// Type of message.
    /// </summary>
    [JsonPropertyName("type")]
    public MessageType Type { get; set; }
    
    /// <summary>
    /// Sent with Rich Presence-related chat embeds.
    /// </summary>
    [JsonPropertyName("activity")]
    public MessageActivity? Activity { get; set; }
    
    /// <summary>
    /// Sent with Rich Presence-related chat embeds.
    /// </summary>
    [JsonPropertyName("application")]
    public MessageApplication? Application { get; set; }
    
    /// <summary>
    /// Interactive components attached to this message (buttons, select menus, etc.).
    /// </summary>
    [JsonPropertyName("components")]
    public List<MessageComponent>? Components { get; set; }
    
    /// <summary>
    /// Message flags combined as a bitfield.
    /// </summary>
    [JsonPropertyName("flags")]
    public MessageFlags? Flags { get; set; }
    
    /// <summary>
    /// The message associated with the message_reference.
    /// </summary>
    [JsonPropertyName("referenced_message")]
    public Message? ReferencedMessage { get; set; }
    
    /// <summary>
    /// The thread that was started from this message.
    /// </summary>
    [JsonPropertyName("thread")]
    public Channel? Thread { get; set; }
    
    /// <summary>
    /// If the message is a response to an interaction, this is the id of the interaction's application.
    /// </summary>
    [JsonPropertyName("application_id")]
    public ulong? ApplicationId { get; set; }
    
    /// <summary>
    /// Id of the guild the message was sent in.
    /// </summary>
    [JsonPropertyName("guild_id")]
    [JsonConverter(typeof(NullableSnowflakeJsonConverter))]
    public ulong? GuildId { get; set; }

    /// <summary>
    /// A poll attached to this message.
    /// </summary>
    [JsonPropertyName("poll")]
    public Poll? Poll { get; set; }

    /// <summary>
    /// Interaction that triggered this message (deprecated; use <see cref="InteractionMetadata"/>).
    /// </summary>
    [JsonPropertyName("interaction")]
    public MessageInteraction? Interaction { get; set; }

    /// <summary>
    /// Metadata about the interaction that generated this message (replaces <see cref="Interaction"/>).
    /// </summary>
    [JsonPropertyName("interaction_metadata")]
    public InteractionMetadata? InteractionMetadata { get; set; }

    /// <summary>
    /// Data about role subscription purchase/renewal that triggered this system message.
    /// </summary>
    [JsonPropertyName("role_subscription_data")]
    public RoleSubscriptionData? RoleSubscriptionData { get; set; }

    /// <summary>
    /// Call data for CALL type messages.
    /// </summary>
    [JsonPropertyName("call")]
    public MessageCall? Call { get; set; }

    /// <summary>
    /// Snapshots of forwarded messages (populated when <see cref="Enums.MessageType"/> is <c>24</c>).
    /// </summary>
    [JsonPropertyName("message_snapshots")]
    public List<MessageSnapshot>? MessageSnapshots { get; set; }

    /// <summary>
    /// Sticker items attached to this message (partial sticker info).
    /// </summary>
    [JsonPropertyName("sticker_items")]
    public List<StickerItem>? StickerItems { get; set; }

    /// <summary>Channels specifically mentioned in a crosspost announcement message.</summary>
    [JsonPropertyName("mention_channels")]
    public List<ChannelMention>? MentionChannels { get; set; }

    /// <summary>Approximate position of this message in a thread, used for jump-to-message.</summary>
    [JsonPropertyName("position")]
    public int? Position { get; set; }
}

/// <summary>
/// Represents a message attachment.
/// </summary>
public class Attachment
{
    [JsonPropertyName("id")]
    [JsonConverter(typeof(SnowflakeJsonConverter))]
    public ulong Id { get; set; }
    
    [JsonPropertyName("filename")]
    public string Filename { get; set; } = string.Empty;
    
    [JsonPropertyName("description")]
    public string? Description { get; set; }
    
    [JsonPropertyName("content_type")]
    public string? ContentType { get; set; }
    
    [JsonPropertyName("size")]
    public int Size { get; set; }
    
    [JsonPropertyName("url")]
    public string Url { get; set; } = string.Empty;
    
    [JsonPropertyName("proxy_url")]
    public string ProxyUrl { get; set; } = string.Empty;
    
    [JsonPropertyName("height")]
    public int? Height { get; set; }
    
    [JsonPropertyName("width")]
    public int? Width { get; set; }
    
    [JsonPropertyName("ephemeral")]
    public bool? Ephemeral { get; set; }
}

/// <summary>
/// Represents a message embed.
/// </summary>
public class Embed
{
    [JsonPropertyName("title")]
    public string? Title { get; set; }
    
    [JsonPropertyName("type")]
    public string? Type { get; set; }
    
    [JsonPropertyName("description")]
    public string? Description { get; set; }
    
    [JsonPropertyName("url")]
    public string? Url { get; set; }
    
    [JsonPropertyName("timestamp")]
    public DateTimeOffset? Timestamp { get; set; }
    
    [JsonPropertyName("color")]
    public int? Color { get; set; }
    
    [JsonPropertyName("footer")]
    public EmbedFooter? Footer { get; set; }
    
    [JsonPropertyName("image")]
    public EmbedImage? Image { get; set; }
    
    [JsonPropertyName("thumbnail")]
    public EmbedThumbnail? Thumbnail { get; set; }
    
    [JsonPropertyName("video")]
    public EmbedVideo? Video { get; set; }
    
    [JsonPropertyName("provider")]
    public EmbedProvider? Provider { get; set; }
    
    [JsonPropertyName("author")]
    public EmbedAuthor? Author { get; set; }
    
    [JsonPropertyName("fields")]
    public List<EmbedField>? Fields { get; set; }
}

public class EmbedFooter
{
    [JsonPropertyName("text")]
    public string Text { get; set; } = string.Empty;
    
    [JsonPropertyName("icon_url")]
    public string? IconUrl { get; set; }
    
    [JsonPropertyName("proxy_icon_url")]
    public string? ProxyIconUrl { get; set; }
}

public class EmbedImage
{
    [JsonPropertyName("url")]
    public string Url { get; set; } = string.Empty;
    
    [JsonPropertyName("proxy_url")]
    public string? ProxyUrl { get; set; }
    
    [JsonPropertyName("height")]
    public int? Height { get; set; }
    
    [JsonPropertyName("width")]
    public int? Width { get; set; }
}

public class EmbedThumbnail
{
    [JsonPropertyName("url")]
    public string Url { get; set; } = string.Empty;
    
    [JsonPropertyName("proxy_url")]
    public string? ProxyUrl { get; set; }
    
    [JsonPropertyName("height")]
    public int? Height { get; set; }
    
    [JsonPropertyName("width")]
    public int? Width { get; set; }
}

public class EmbedVideo
{
    [JsonPropertyName("url")]
    public string? Url { get; set; }
    
    [JsonPropertyName("proxy_url")]
    public string? ProxyUrl { get; set; }
    
    [JsonPropertyName("height")]
    public int? Height { get; set; }
    
    [JsonPropertyName("width")]
    public int? Width { get; set; }
}

public class EmbedProvider
{
    [JsonPropertyName("name")]
    public string? Name { get; set; }
    
    [JsonPropertyName("url")]
    public string? Url { get; set; }
}

public class EmbedAuthor
{
    [JsonPropertyName("name")]
    public string Name { get; set; } = string.Empty;
    
    [JsonPropertyName("url")]
    public string? Url { get; set; }
    
    [JsonPropertyName("icon_url")]
    public string? IconUrl { get; set; }
    
    [JsonPropertyName("proxy_icon_url")]
    public string? ProxyIconUrl { get; set; }
}

public class EmbedField
{
    [JsonPropertyName("name")]
    public string Name { get; set; } = string.Empty;
    
    [JsonPropertyName("value")]
    public string Value { get; set; } = string.Empty;
    
    [JsonPropertyName("inline")]
    public bool? Inline { get; set; }
}

/// <summary>
/// Represents a message reaction.
/// </summary>
public class Reaction
{
    [JsonPropertyName("count")]
    public int Count { get; set; }
    
    [JsonPropertyName("me")]
    public bool Me { get; set; }
    
    [JsonPropertyName("emoji")]
    public Emoji Emoji { get; set; } = null!;
}

// ── Interaction data attached to messages ─────────────────────────────────────

/// <summary>
/// Deprecated interaction data attached to a message response.
/// Use <see cref="InteractionMetadata"/> for new implementations.
/// </summary>
public class MessageInteraction
{
    [JsonPropertyName("id")]
    [JsonConverter(typeof(SnowflakeJsonConverter))]
    public ulong Id { get; set; }

    /// <summary>Interaction type (see Discord docs InteractionType enum).</summary>
    [JsonPropertyName("type")]
    public int Type { get; set; }

    /// <summary>Name of the application command or component custom_id.</summary>
    [JsonPropertyName("name")]
    public string Name { get; set; } = string.Empty;

    /// <summary>User who invoked the interaction.</summary>
    [JsonPropertyName("user")]
    public User User { get; set; } = null!;

    /// <summary>Member who invoked the interaction (guild interactions only).</summary>
    [JsonPropertyName("member")]
    public GuildMember? Member { get; set; }
}

/// <summary>
/// Metadata about the interaction that generated a message response (replaces MessageInteraction).
/// </summary>
public class InteractionMetadata
{
    [JsonPropertyName("id")]
    [JsonConverter(typeof(SnowflakeJsonConverter))]
    public ulong Id { get; set; }

    /// <summary>Interaction type value.</summary>
    [JsonPropertyName("type")]
    public int Type { get; set; }

    /// <summary>ID of the user who triggered the interaction.</summary>
    [JsonPropertyName("user_id")]
    [JsonConverter(typeof(SnowflakeJsonConverter))]
    public ulong UserId { get; set; }

    /// <summary>
    /// Dictionary of installation contexts to authorizing user/guild IDs.
    /// Key 0 = guild install context, Key 1 = user install context.
    /// </summary>
    [JsonPropertyName("authorizing_integration_owners")]
    public System.Collections.Generic.Dictionary<string, ulong>? AuthorizingIntegrationOwners { get; set; }

    /// <summary>ID of the original response message for a follow-up interaction.</summary>
    [JsonPropertyName("original_response_message_id")]
    [JsonConverter(typeof(NullableSnowflakeJsonConverter))]
    public ulong? OriginalResponseMessageId { get; set; }

    /// <summary>ID of the message that was interacted with (component interactions).</summary>
    [JsonPropertyName("interacted_message_id")]
    [JsonConverter(typeof(NullableSnowflakeJsonConverter))]
    public ulong? InteractedMessageId { get; set; }

    /// <summary>Metadata for the interaction that triggered a modal from this interaction.</summary>
    [JsonPropertyName("triggering_interaction_metadata")]
    public InteractionMetadata? TriggeringInteractionMetadata { get; set; }
}

// ── Role subscription data ────────────────────────────────────────────────────

/// <summary>
/// Data about a role subscription purchase or renewal that triggered a system message.
/// </summary>
public class RoleSubscriptionData
{
    /// <summary>ID of the SKU and listing that the user subscribed to.</summary>
    [JsonPropertyName("role_subscription_listing_id")]
    [JsonConverter(typeof(SnowflakeJsonConverter))]
    public ulong RoleSubscriptionListingId { get; set; }

    /// <summary>Name of the tier that the user subscribed to.</summary>
    [JsonPropertyName("tier_name")]
    public string TierName { get; set; } = string.Empty;

    /// <summary>Cumulative number of months the user has been subscribed for.</summary>
    [JsonPropertyName("total_months_subscribed")]
    public int TotalMonthsSubscribed { get; set; }

    /// <summary>Whether this notification is for a renewal rather than a new purchase.</summary>
    [JsonPropertyName("is_renewal")]
    public bool IsRenewal { get; set; }
}

// ── Message call data ─────────────────────────────────────────────────────────

/// <summary>
/// Call information for CALL type messages (DM voice calls).
/// </summary>
public class MessageCall
{
    /// <summary>Array of user IDs that participated in the call.</summary>
    [JsonPropertyName("participants")]
    [JsonConverter(typeof(SnowflakeListJsonConverter))]
    public System.Collections.Generic.List<ulong> Participants { get; set; } = new();

    /// <summary>Time when the call ended (null if still in progress).</summary>
    [JsonPropertyName("ended_timestamp")]
    public DateTimeOffset? EndedTimestamp { get; set; }
}

// ── Message snapshot (forwarded messages) ─────────────────────────────────────

/// <summary>
/// A snapshot containing a partial copy of a forwarded message
/// (MessageType 24 = ForwardedMessage).
/// </summary>
public class MessageSnapshot
{
    /// <summary>Partial message data from the forwarded message.</summary>
    [JsonPropertyName("message")]
    public PartialMessage Message { get; set; } = null!;
}

/// <summary>
/// A partial message object used inside <see cref="MessageSnapshot"/>.
/// Contains the subset of message fields Discord sends for forwarded messages.
/// </summary>
public class PartialMessage
{
    [JsonPropertyName("type")]
    public Enums.MessageType Type { get; set; }

    [JsonPropertyName("content")]
    public string Content { get; set; } = string.Empty;

    [JsonPropertyName("embeds")]
    public System.Collections.Generic.List<Embed>? Embeds { get; set; }

    [JsonPropertyName("attachments")]
    public System.Collections.Generic.List<Attachment>? Attachments { get; set; }

    [JsonPropertyName("timestamp")]
    public DateTimeOffset Timestamp { get; set; }

    [JsonPropertyName("edited_timestamp")]
    public DateTimeOffset? EditedTimestamp { get; set; }

    [JsonPropertyName("flags")]
    public Enums.MessageFlags? Flags { get; set; }

    [JsonPropertyName("mentions")]
    public System.Collections.Generic.List<User>? Mentions { get; set; }

    [JsonPropertyName("mention_roles")]
    public System.Collections.Generic.List<ulong>? MentionRoles { get; set; }

    [JsonPropertyName("components")]
    public System.Collections.Generic.List<MessageComponent>? Components { get; set; }

    [JsonPropertyName("sticker_items")]
    public System.Collections.Generic.List<StickerItem>? StickerItems { get; set; }
}

// ── Channel mention (crosspost) ───────────────────────────────────────────────

/// <summary>
/// A reference to a channel mentioned inside a crosspost announcement message.
/// </summary>
public class ChannelMention
{
    [JsonPropertyName("id")]
    [JsonConverter(typeof(SnowflakeJsonConverter))]
    public ulong Id { get; set; }

    [JsonPropertyName("guild_id")]
    [JsonConverter(typeof(SnowflakeJsonConverter))]
    public ulong GuildId { get; set; }

    [JsonPropertyName("type")]
    public Enums.ChannelType Type { get; set; }

    [JsonPropertyName("name")]
    public string Name { get; set; } = string.Empty;
}
