#nullable enable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;
using PawSharp.Core.Enums;
using PawSharp.Core.Serialization;

namespace PawSharp.Core.Entities;

/// <summary>
/// Represents a Discord message.
/// </summary>
public class Message : DiscordEntity
{
    /// <summary>
    /// Id of the channel the message was sent in.
    /// </summary>
    [JsonPropertyName("channel_id")]
    public ulong ChannelId { get; set; }
    
    /// <summary>
    /// The author of this message.
    /// </summary>
    [JsonPropertyName("author")]
    public User Author { get; set; } = null!;
    
    /// <summary>
    /// Contents of the message.
    /// </summary>
    [JsonPropertyName("content")]
    public string Content { get; set; } = string.Empty;
    
    /// <summary>
    /// When this message was sent.
    /// </summary>
    [JsonPropertyName("timestamp")]
    public DateTimeOffset Timestamp { get; set; }
    
    /// <summary>
    /// When this message was edited (or null if never).
    /// </summary>
    [JsonPropertyName("edited_timestamp")]
    public DateTimeOffset? EditedTimestamp { get; set; }
    
    /// <summary>
    /// Whether this was a TTS message.
    /// </summary>
    [JsonPropertyName("tts")]
    public bool Tts { get; set; }
    
    /// <summary>
    /// Whether this message mentions everyone.
    /// </summary>
    [JsonPropertyName("mention_everyone")]
    public bool MentionEveryone { get; set; }
    
    /// <summary>
    /// Users specifically mentioned in the message.
    /// </summary>
    [JsonPropertyName("mentions")]
    public List<User> Mentions { get; set; } = new();
    
    /// <summary>
    /// Roles specifically mentioned in this message.
    /// </summary>
    [JsonPropertyName("mention_roles")]
    public List<ulong> MentionRoles { get; set; } = new();
    
    /// <summary>
    /// Any attached files.
    /// </summary>
    [JsonPropertyName("attachments")]
    public List<Attachment> Attachments { get; set; } = new();
    
    /// <summary>
    /// Any embedded content.
    /// </summary>
    [JsonPropertyName("embeds")]
    public List<Embed> Embeds { get; set; } = new();
    
    /// <summary>
    /// Reactions to the message.
    /// </summary>
    [JsonPropertyName("reactions")]
    public List<Reaction>? Reactions { get; set; }
    
    /// <summary>
    /// Used for validating a message was sent.
    /// </summary>
    [JsonPropertyName("nonce")]
    public string? Nonce { get; set; }
    
    /// <summary>
    /// Whether this message is pinned.
    /// </summary>
    [JsonPropertyName("pinned")]
    public bool Pinned { get; set; }
    
    /// <summary>
    /// If the message is generated by a webhook, this is the webhook's id.
    /// </summary>
    [JsonPropertyName("webhook_id")]
    public ulong? WebhookId { get; set; }
    
    /// <summary>
    /// Type of message.
    /// </summary>
    [JsonPropertyName("type")]
    public MessageType Type { get; set; }
    
    /// <summary>
    /// Sent with Rich Presence-related chat embeds.
    /// </summary>
    [JsonPropertyName("activity")]
    public object? Activity { get; set; }
    
    /// <summary>
    /// Sent with Rich Presence-related chat embeds.
    /// </summary>
    [JsonPropertyName("application")]
    public object? Application { get; set; }
    
    /// <summary>
    /// Message components like buttons.
    /// </summary>
    [JsonPropertyName("components")]
    public List<object>? Components { get; set; }
    
    /// <summary>
    /// Message flags combined as a bitfield.
    /// </summary>
    [JsonPropertyName("flags")]
    public int? Flags { get; set; }
    
    /// <summary>
    /// The message associated with the message_reference.
    /// </summary>
    [JsonPropertyName("referenced_message")]
    public Message? ReferencedMessage { get; set; }
    
    /// <summary>
    /// The thread that was started from this message.
    /// </summary>
    [JsonPropertyName("thread")]
    public Channel? Thread { get; set; }
    
    /// <summary>
    /// If the message is a response to an interaction, this is the id of the interaction's application.
    /// </summary>
    [JsonPropertyName("application_id")]
    public ulong? ApplicationId { get; set; }
    
    /// <summary>
    /// Id of the guild the message was sent in.
    /// </summary>
    [JsonPropertyName("guild_id")]
    [JsonConverter(typeof(NullableSnowflakeJsonConverter))]
    public ulong? GuildId { get; set; }
}

/// <summary>
/// Represents a message attachment.
/// </summary>
public class Attachment
{
    [JsonPropertyName("id")]
    [JsonConverter(typeof(SnowflakeJsonConverter))]
    public ulong Id { get; set; }
    
    [JsonPropertyName("filename")]
    public string Filename { get; set; } = string.Empty;
    
    [JsonPropertyName("description")]
    public string? Description { get; set; }
    
    [JsonPropertyName("content_type")]
    public string? ContentType { get; set; }
    
    [JsonPropertyName("size")]
    public int Size { get; set; }
    
    [JsonPropertyName("url")]
    public string Url { get; set; } = string.Empty;
    
    [JsonPropertyName("proxy_url")]
    public string ProxyUrl { get; set; } = string.Empty;
    
    [JsonPropertyName("height")]
    public int? Height { get; set; }
    
    [JsonPropertyName("width")]
    public int? Width { get; set; }
    
    [JsonPropertyName("ephemeral")]
    public bool? Ephemeral { get; set; }
}

/// <summary>
/// Represents a message embed.
/// </summary>
public class Embed
{
    [JsonPropertyName("title")]
    public string? Title { get; set; }
    
    [JsonPropertyName("type")]
    public string? Type { get; set; }
    
    [JsonPropertyName("description")]
    public string? Description { get; set; }
    
    [JsonPropertyName("url")]
    public string? Url { get; set; }
    
    [JsonPropertyName("timestamp")]
    public DateTimeOffset? Timestamp { get; set; }
    
    [JsonPropertyName("color")]
    public int? Color { get; set; }
    
    [JsonPropertyName("footer")]
    public EmbedFooter? Footer { get; set; }
    
    [JsonPropertyName("image")]
    public EmbedImage? Image { get; set; }
    
    [JsonPropertyName("thumbnail")]
    public EmbedThumbnail? Thumbnail { get; set; }
    
    [JsonPropertyName("video")]
    public EmbedVideo? Video { get; set; }
    
    [JsonPropertyName("provider")]
    public EmbedProvider? Provider { get; set; }
    
    [JsonPropertyName("author")]
    public EmbedAuthor? Author { get; set; }
    
    [JsonPropertyName("fields")]
    public List<EmbedField>? Fields { get; set; }
}

public class EmbedFooter
{
    [JsonPropertyName("text")]
    public string Text { get; set; } = string.Empty;
    
    [JsonPropertyName("icon_url")]
    public string? IconUrl { get; set; }
    
    [JsonPropertyName("proxy_icon_url")]
    public string? ProxyIconUrl { get; set; }
}

public class EmbedImage
{
    [JsonPropertyName("url")]
    public string Url { get; set; } = string.Empty;
    
    [JsonPropertyName("proxy_url")]
    public string? ProxyUrl { get; set; }
    
    [JsonPropertyName("height")]
    public int? Height { get; set; }
    
    [JsonPropertyName("width")]
    public int? Width { get; set; }
}

public class EmbedThumbnail
{
    [JsonPropertyName("url")]
    public string Url { get; set; } = string.Empty;
    
    [JsonPropertyName("proxy_url")]
    public string? ProxyUrl { get; set; }
    
    [JsonPropertyName("height")]
    public int? Height { get; set; }
    
    [JsonPropertyName("width")]
    public int? Width { get; set; }
}

public class EmbedVideo
{
    [JsonPropertyName("url")]
    public string? Url { get; set; }
    
    [JsonPropertyName("proxy_url")]
    public string? ProxyUrl { get; set; }
    
    [JsonPropertyName("height")]
    public int? Height { get; set; }
    
    [JsonPropertyName("width")]
    public int? Width { get; set; }
}

public class EmbedProvider
{
    [JsonPropertyName("name")]
    public string? Name { get; set; }
    
    [JsonPropertyName("url")]
    public string? Url { get; set; }
}

public class EmbedAuthor
{
    [JsonPropertyName("name")]
    public string Name { get; set; } = string.Empty;
    
    [JsonPropertyName("url")]
    public string? Url { get; set; }
    
    [JsonPropertyName("icon_url")]
    public string? IconUrl { get; set; }
    
    [JsonPropertyName("proxy_icon_url")]
    public string? ProxyIconUrl { get; set; }
}

public class EmbedField
{
    [JsonPropertyName("name")]
    public string Name { get; set; } = string.Empty;
    
    [JsonPropertyName("value")]
    public string Value { get; set; } = string.Empty;
    
    [JsonPropertyName("inline")]
    public bool? Inline { get; set; }
}

/// <summary>
/// Represents a message reaction.
/// </summary>
public class Reaction
{
    [JsonPropertyName("count")]
    public int Count { get; set; }
    
    [JsonPropertyName("me")]
    public bool Me { get; set; }
    
    [JsonPropertyName("emoji")]
    public Emoji Emoji { get; set; } = null!;
}

/// <summary>
/// Represents an emoji.
/// </summary>
public class Emoji
{
    [JsonPropertyName("id")]
    [JsonConverter(typeof(NullableSnowflakeJsonConverter))]
    public ulong? Id { get; set; }
    
    [JsonPropertyName("name")]
    public string? Name { get; set; }
    
    [JsonPropertyName("roles")]
    [JsonConverter(typeof(SnowflakeListJsonConverter))]
    public List<ulong>? Roles { get; set; }
    
    [JsonPropertyName("user")]
    public User? User { get; set; }
    
    [JsonPropertyName("require_colons")]
    public bool? RequireColons { get; set; }
    
    [JsonPropertyName("managed")]
    public bool? Managed { get; set; }
    
    [JsonPropertyName("animated")]
    public bool? Animated { get; set; }
    
    [JsonPropertyName("available")]
    public bool? Available { get; set; }
}
