<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>PawSharp.Voice</RootNamespace>
    <AssemblyName>PawSharp.Voice</AssemblyName>
    <PackageId>PawSharp.Voice</PackageId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\PawSharp.Core\PawSharp.Core.csproj" />
    <ProjectReference Include="..\PawSharp.API\PawSharp.API.csproj" />
    <ProjectReference Include="..\PawSharp.Gateway\PawSharp.Gateway.csproj" />
    <ProjectReference Include="..\PawSharp.Client\PawSharp.Client.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Concentus" Version="1.0.4" />
    <PackageReference Include="NAudio" Version="2.2.1" />
  </ItemGroup>

</Project>