#nullable enable
using System.Text.Json.Serialization;
using PawSharp.Gateway.Events;

namespace PawSharp.Gateway.Serialization;

/// <summary>
/// Source-generated JSON serialization context for PawSharp Gateway events.
/// Enables Native AOT compatibility by eliminating reflection-based serialization.
/// </summary>
[JsonSerializable(typeof(ReadyEvent))]
[JsonSerializable(typeof(ResumedEvent))]
[JsonSerializable(typeof(MessageCreateEvent))]
[JsonSerializable(typeof(MessageUpdateEvent))]
[JsonSerializable(typeof(MessageDeleteEvent))]
[JsonSerializable(typeof(MessageDeleteBulkEvent))]
[JsonSerializable(typeof(GuildCreateEvent))]
[JsonSerializable(typeof(GuildUpdateEvent))]
[JsonSerializable(typeof(GuildDeleteEvent))]
[JsonSerializable(typeof(GuildAvailableEvent))]
[JsonSerializable(typeof(GuildUnavailableEvent))]
[JsonSerializable(typeof(GuildEmojisUpdateEvent))]
[JsonSerializable(typeof(ChannelCreateEvent))]
[JsonSerializable(typeof(ChannelUpdateEvent))]
[JsonSerializable(typeof(ChannelDeleteEvent))]
[JsonSerializable(typeof(GuildMemberAddEvent))]
[JsonSerializable(typeof(GuildMemberUpdateEvent))]
[JsonSerializable(typeof(GuildMemberRemoveEvent))]
[JsonSerializable(typeof(GuildMembersChunkEvent))]
[JsonSerializable(typeof(InteractionCreateEvent))]
[JsonSerializable(typeof(TypingStartEvent))]
[JsonSerializable(typeof(MessageReactionAddEvent))]
[JsonSerializable(typeof(MessageReactionRemoveEvent))]
[JsonSerializable(typeof(MessageReactionRemoveAllEvent))]
[JsonSerializable(typeof(MessageReactionRemoveEmojiEvent))]
[JsonSerializable(typeof(PresenceUpdateEvent))]
[JsonSerializable(typeof(ChannelPinsUpdateEvent))]
[JsonSerializable(typeof(GuildBanAddEvent))]
[JsonSerializable(typeof(GuildBanRemoveEvent))]
[JsonSerializable(typeof(GuildRoleCreateEvent))]
[JsonSerializable(typeof(GuildRoleUpdateEvent))]
[JsonSerializable(typeof(GuildRoleDeleteEvent))]
[JsonSerializable(typeof(GuildStickersUpdateEvent))]
[JsonSerializable(typeof(GuildIntegrationsUpdateEvent))]
[JsonSerializable(typeof(VoiceStateUpdateEvent))]
[JsonSerializable(typeof(VoiceServerUpdateEvent))]
[JsonSerializable(typeof(ThreadCreateEvent))]
[JsonSerializable(typeof(ThreadUpdateEvent))]
[JsonSerializable(typeof(ThreadDeleteEvent))]
[JsonSerializable(typeof(ThreadListSyncEvent))]
[JsonSerializable(typeof(ThreadMemberUpdateEvent))]
[JsonSerializable(typeof(ThreadMembersUpdateEvent))]
[JsonSerializable(typeof(GuildScheduledEventCreateEvent))]
[JsonSerializable(typeof(GuildScheduledEventUpdateEvent))]
[JsonSerializable(typeof(GuildScheduledEventDeleteEvent))]
[JsonSerializable(typeof(GuildScheduledEventUserAddEvent))]
[JsonSerializable(typeof(GuildScheduledEventUserRemoveEvent))]
[JsonSerializable(typeof(AutoModerationRuleCreateEvent))]
[JsonSerializable(typeof(AutoModerationRuleUpdateEvent))]
[JsonSerializable(typeof(AutoModerationRuleDeleteEvent))]
[JsonSerializable(typeof(AutoModerationActionExecutionEvent))]
[JsonSerializable(typeof(StageInstanceCreateEvent))]
[JsonSerializable(typeof(StageInstanceUpdateEvent))]
[JsonSerializable(typeof(StageInstanceDeleteEvent))]
[JsonSerializable(typeof(GuildAuditLogEntryCreateEvent))]
[JsonSerializable(typeof(EntitlementCreateEvent))]
[JsonSerializable(typeof(EntitlementUpdateEvent))]
[JsonSerializable(typeof(EntitlementDeleteEvent))]
[JsonSerializable(typeof(MessagePollVoteAddEvent))]
[JsonSerializable(typeof(MessagePollVoteRemoveEvent))]
[JsonSerializable(typeof(GuildSoundboardSoundCreateEvent))]
[JsonSerializable(typeof(GuildSoundboardSoundUpdateEvent))]
[JsonSerializable(typeof(GuildSoundboardSoundDeleteEvent))]
[JsonSerializable(typeof(GuildSoundboardSoundsUpdateEvent))]
[JsonSerializable(typeof(VoiceChannelEffectSendEvent))]
[JsonSerializable(typeof(VoiceChannelStatusUpdateEvent))]
[JsonSerializable(typeof(SubscriptionCreateEvent))]
[JsonSerializable(typeof(SubscriptionUpdateEvent))]
[JsonSerializable(typeof(SubscriptionDeleteEvent))]
[JsonSerializable(typeof(InviteCreateEvent))]
[JsonSerializable(typeof(InviteDeleteEvent))]
[JsonSerializable(typeof(WebhooksUpdateEvent))]
[JsonSerializable(typeof(ApplicationCommandPermissionsUpdateEvent))]
[JsonSerializable(typeof(GuildAppCommandCreateEvent))]
[JsonSerializable(typeof(GuildAppCommandUpdateEvent))]
[JsonSerializable(typeof(GuildAppCommandDeleteEvent))]
[JsonSerializable(typeof(IntegrationCreateEvent))]
[JsonSerializable(typeof(IntegrationUpdateEvent))]
[JsonSerializable(typeof(IntegrationDeleteEvent))]
[JsonSerializable(typeof(UserUpdateEvent))]
public partial class PawSharpGatewayJsonContext : JsonSerializerContext
{
}
